# Generated by Django 3.2.4 on 2026-04-11 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variants', '0020_auto_20260410_1130'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='название')),
                ('instructions', models.TextField(blank=True, verbose_name='инструкции')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='дедлайн')),
                ('allow_late_submissions', models.BooleanField(default=True, verbose_name='разрешить сдачу после дедлайна')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('published', 'назначено'), ('archived', 'в архиве')], default='published', max_length=20, verbose_name='статус')),
                ('max_score_strategy', models.CharField(choices=[('auto', 'автоматически по задачам'), ('manual', 'вручную')], default='auto', max_length=20, verbose_name='как считать максимум')),
                ('manual_max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='максимум баллов вручную')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homework_assignments', to=settings.AUTH_USER_MODEL, verbose_name='кто назначил')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='homework_assignments', to='accounts.StudyGroup', verbose_name='назначенные группы')),
                ('target_students', models.ManyToManyField(blank=True, related_name='direct_homework_assignments', to=settings.AUTH_USER_MODEL, verbose_name='назначенные ученики')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_assignments', to='variants.variant', verbose_name='вариант')),
            ],
            options={
                'verbose_name': 'назначение ДЗ',
                'verbose_name_plural': 'назначения ДЗ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'назначено'), ('draft', 'черновик'), ('submitted', 'сдано'), ('under_review', 'на проверке'), ('reviewed', 'проверено'), ('returned', 'возвращено на доработку'), ('deleted', 'удалено учеником')], default='assigned', max_length=20, verbose_name='статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='когда сдано')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='когда проверено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='когда удалено')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='когда восстановлено')),
                ('last_student_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя активность ученика')),
                ('last_teacher_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя активность учителя')),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='автоматический балл')),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='ручной балл')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='итоговый балл')),
                ('max_score_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='максимум баллов на момент назначения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homeworkassignment', verbose_name='назначение')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'сдача ДЗ',
                'verbose_name_plural': 'сдачи ДЗ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_comments', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homework.homeworksubmission', verbose_name='сдача')),
            ],
            options={
                'verbose_name': 'комментарий к сдаче',
                'verbose_name_plural': 'комментарии к сдаче',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'создано'), ('draft_saved', 'черновик сохранен'), ('submitted', 'сдано'), ('edited', 'отредактировано'), ('deleted', 'удалено'), ('restored', 'восстановлено'), ('review_started', 'проверка начата'), ('reviewed', 'проверено'), ('comment_added', 'добавлен комментарий'), ('status_changed', 'смена статуса')], max_length=30, verbose_name='тип события')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='данные события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_events', to=settings.AUTH_USER_MODEL, verbose_name='кто сделал')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='homework.homeworksubmission', verbose_name='сдача')),
            ],
            options={
                'verbose_name': 'событие сдачи',
                'verbose_name_plural': 'события сдач',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionCommentRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='когда прочитано')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='homework.submissioncomment', verbose_name='комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_read_receipts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'прочтение комментария',
                'verbose_name_plural': 'прочтения комментариев',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework/submissions/%Y/%m/%d/', verbose_name='файл')),
                ('rotation_degrees', models.PositiveSmallIntegerField(default=0, verbose_name='поворот')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='homework.homeworksubmission', verbose_name='сдача')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_submission_attachments', to=settings.AUTH_USER_MODEL, verbose_name='кто загрузил')),
            ],
            options={
                'verbose_name': 'вложение к сдаче',
                'verbose_name_plural': 'вложения к сдаче',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='submissioncommentread',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_submission_comment_read_receipt'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_homework_submission_per_student'),
        ),
    ]
