# Generated by Codex on 2026-04-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0029_auto_20260406_0534'),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='ответ ученика')),
                ('normalized_answer', models.TextField(blank=True, verbose_name='нормализованный ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='верно')),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='начислено баллов')),
                ('max_score_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='максимум баллов')),
                ('evaluation_payload', models.JSONField(blank=True, default=dict, verbose_name='детали проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_answers', to='problems.problem', verbose_name='задача')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='homework.homeworksubmission', verbose_name='сдача')),
            ],
            options={
                'verbose_name': 'ответ в сдаче',
                'verbose_name_plural': 'ответы в сдаче',
                'ordering': ['problem_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='homeworksubmissionanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'problem'), name='unique_submission_answer_per_problem'),
        ),
    ]
