# Generated by Codex on 2026-04-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0029_auto_20260406_0534'),
        ('homework', '0002_homeworksubmissionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkassignment',
            name='allow_second_part_text',
            field=models.BooleanField(default=False, verbose_name='разрешить печатать вторую часть текстом'),
        ),
        migrations.AddField(
            model_name='homeworkassignment',
            name='second_part_mode',
            field=models.CharField(choices=[('single_file', 'вся вторая часть одним блоком'), ('per_problem', 'отдельно по каждому заданию')], default='single_file', max_length=20, verbose_name='как сдавать вторую часть'),
        ),
        migrations.AddField(
            model_name='submissionattachment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_attachments', to='problems.problem', verbose_name='задача'),
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionSecondPartResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='текст ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_part_responses', to='problems.problem', verbose_name='задача')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_part_responses', to='homework.homeworksubmission', verbose_name='сдача')),
            ],
            options={
                'verbose_name': 'ответ второй части',
                'verbose_name_plural': 'ответы второй части',
                'ordering': ['problem_id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionSecondPartScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='балл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_part_scores', to='problems.problem', verbose_name='задача')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_part_scores', to='homework.homeworksubmission', verbose_name='сдача')),
            ],
            options={
                'verbose_name': 'балл второй части',
                'verbose_name_plural': 'баллы второй части',
                'ordering': ['problem_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='homeworksubmissionsecondpartresponse',
            constraint=models.UniqueConstraint(fields=('submission', 'problem'), name='unique_second_part_response_per_problem'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmissionsecondpartscore',
            constraint=models.UniqueConstraint(fields=('submission', 'problem'), name='unique_second_part_score_per_problem'),
        ),
    ]
