# Generated by Codex on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_second_part_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncomment',
            name='image',
            field=models.FileField(blank=True, upload_to='homework/comments/%Y/%m/%d/', verbose_name='картинка'),
        ),
    ]
