# Generated by Django 3.2.4 on 2026-04-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_submissioncomment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkassignment',
            name='second_part_mode',
            field=models.CharField(choices=[('single_file', 'одним общим файлом'), ('per_problem', 'обязательно отдельно файл по каждому заданию'), ('flexible', 'можно и отдельно, и все одним файлом')], default='single_file', max_length=20, verbose_name='как сдавать вторую часть'),
        ),
    ]
