# Generated by Django 3.2.4 on 2026-04-18 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0030_cleanup_reference_data'),
        ('homework', '0005_alter_homeworkassignment_second_part_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('submitted', 'проверено для себя')], default='draft', max_length=20, verbose_name='статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='когда проверено')),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='автоматический балл')),
                ('max_score_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='максимум баллов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='homework.homeworkassignment', verbose_name='назначение')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_practice_attempts', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'личная попытка',
                'verbose_name_plural': 'личные попытки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkPracticeAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='ответ ученика')),
                ('normalized_answer', models.TextField(blank=True, verbose_name='нормализованный ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='верно')),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='начислено баллов')),
                ('max_score_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='максимум баллов')),
                ('evaluation_payload', models.JSONField(blank=True, default=dict, verbose_name='детали проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='homework.homeworkpracticeattempt', verbose_name='попытка')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempt_answers', to='problems.problem', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'ответ в личной попытке',
                'verbose_name_plural': 'ответы в личных попытках',
                'ordering': ['problem_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='homeworkpracticeattemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'problem'), name='unique_practice_attempt_answer_per_problem'),
        ),
    ]
