# Generated by Django 3.2.4 on 2026-04-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_auto_20260418_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='student_review_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='когда ученик увидел проверку'),
        ),
    ]
