# Generated by Django 3.2.4 on 2022-12-24 16:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('slug', models.SlugField(help_text='Слаг - текстовый идентификатор,с помощью которого будутгенерироваться ссылки)', max_length=150, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'default_related_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='PartOfEGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
            ],
            options={
                'verbose_name': 'часть',
                'verbose_name_plural': 'части',
                'default_related_name': 'part',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 500 символов', max_length=500, verbose_name='название')),
            ],
            options={
                'verbose_name': 'источник',
                'verbose_name_plural': 'источники',
                'default_related_name': 'source',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('slug', models.SlugField(help_text='Слаг - текстовый идентификатор,с помощью которого будутгенерироваться ссылки)', max_length=150, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
                'default_related_name': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TypeInEGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='номер')),
                ('max_score', models.PositiveSmallIntegerField(verbose_name='максимальное количествобаллов')),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'типы',
                'default_related_name': 'type',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Максимум 6 тыс. символов(если мало - обратитесь к создательнице сайта)', max_length=6000, verbose_name='условие')),
                ('solution', models.TextField(help_text='Максимум 6 тыс. символов', max_length=6000, verbose_name='решение')),
                ('answer', models.CharField(help_text='Максимум 50 символов', max_length=50, verbose_name='ответ')),
                ('complexity', models.IntegerField(help_text='число от 1 до 10 включительно', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='сложность')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.category', verbose_name='категория')),
                ('part_ege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.partofege', verbose_name='часть ЕГЭ')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.source', verbose_name='источник')),
                ('tags', models.ManyToManyField(related_name='problems', to='problems.Tag', verbose_name='тэги')),
                ('type_ege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.typeinege', verbose_name='Тип задания')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'default_related_name': 'problems',
            },
        ),
    ]
