# Generated by Django 3.2.4 on 2022-12-24 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='complexity',
            field=models.PositiveSmallIntegerField(help_text='число от 1 до 10включительно', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='сложность'),
        ),
    ]
