# Generated by Django 3.2.4 on 2022-12-24 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20221224_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='problems.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Слаг - текстовый идентификатор, с помощью которого будут генерироваться ссылки', max_length=150, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Слаг - текстовый идентификатор, с помощью которого будут генерироваться ссылки', max_length=150, verbose_name='слаг'),
        ),
    ]
