# Generated by Django 3.2.4 on 2022-12-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20221224_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.source', verbose_name='источник'),
        ),
    ]
