# Generated by Django 3.2.4 on 2022-12-30 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20221225_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='part_ege',
        ),
        migrations.AddField(
            model_name='typeinege',
            name='part_ege',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='problems.partofege', verbose_name='часть ЕГЭ'),
        ),
    ]
