# Generated by Django 3.2.4 on 2023-01-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_alter_typeinege_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type_ege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.typeinege', verbose_name='Тип задания'),
        ),
    ]
