# Generated by Django 3.2.4 on 2023-01-09 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_alter_problem_type_ege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 150 символов', max_length=150, verbose_name='название')),
                ('slug', models.SlugField(help_text='Слаг - текстовый идентификатор, с помощью которого будут генерироваться ссылки', max_length=150, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'подраздел',
                'verbose_name_plural': 'подразделы',
                'default_related_name': 'subcategory',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'category', 'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.category', verbose_name='раздел'),
        ),
        migrations.AddField(
            model_name='problem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.subcategory', verbose_name='подраздел'),
        ),
    ]
