# Generated by Django 3.2.4 on 2023-01-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0011_auto_20230109_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_image', models.ImageField(default='', upload_to='media/%Y/%m', verbose_name='изображение')),
                ('relation', models.PositiveSmallIntegerField(choices=[(1, 'условию'), (2, 'решению'), (3, 'ответу')], verbose_name='относится к')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem', verbose_name='задача')),
            ],
        ),
    ]
