# Generated by Django 3.2.4 on 2023-01-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20230115_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.TextField(blank=True, help_text='Максимум 1 тыс. символов', max_length=1000, null=True, verbose_name='ответ'),
        ),
    ]
