# Generated by Django 3.2.4 on 2023-01-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_auto_20230114_2343'),
        ('problems', '0014_alter_problem_answer'),
    ]

    operations = [
    ]
