# Generated by Django 3.2.4 on 2023-01-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_merge_20230116_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveSmallIntegerField(default=600, verbose_name='размер в px'),
        ),
    ]
