# Generated by Django 3.2.4 on 2023-01-16 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_image_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'category', 'ordering': ['name'], 'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
        migrations.AlterModelOptions(
            name='partofege',
            options={'default_related_name': 'part', 'ordering': ['-id'], 'verbose_name': 'часть', 'verbose_name_plural': 'части'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'default_related_name': 'source', 'ordering': ['name'], 'verbose_name': 'источник', 'verbose_name_plural': 'источники'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'default_related_name': 'subcategory', 'ordering': ['name'], 'verbose_name': 'подраздел', 'verbose_name_plural': 'подразделы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'ordering': ['name'], 'verbose_name': 'тэг', 'verbose_name_plural': 'тэги'},
        ),
    ]
