# Generated by Django 3.2.4 on 2023-03-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.AlterField(
            model_name='image',
            name='path_to_image',
            field=models.ImageField(default='', upload_to='', verbose_name='изображение'),
        ),
    ]
