# Generated by Django 3.2.4 on 2023-05-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_problemfts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemFTS',
        ),
    ]
