# Generated by Django 3.2.4 on 2023-11-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_delete_problemfts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type_ege',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.typeinege', verbose_name='Тип задания'),
        ),
    ]
