# Generated by Django 3.2.4 on 2024-03-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_alter_problem_type_ege'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='заметки'),
        ),
    ]
