# Generated by Django 3.2.4 on 2024-03-18 18:10

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0023_problem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='similar_problems',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='_problem_similar_problems_+', to='problems.Problem', verbose_name='похожие задачи'),
        ),
    ]
