# Generated by Django 3.2.4 on 2024-03-19 19:45

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0024_problem_similar_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='similar_problems',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='_problem_similar_problems_+', to='problems.Problem', verbose_name='похожие задачи'),
        ),
    ]
