# Generated by Django 3.2.4 on 2026-04-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0025_alter_problem_similar_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, unique=True, verbose_name='фраза обоснования')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'обоснование',
                'verbose_name_plural': 'обоснования',
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='закон / принцип')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'закон',
                'verbose_name_plural': 'законы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemSolutionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='название способа')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('justifications', models.ManyToManyField(blank=True, related_name='solution_methods', to='problems.Justification', verbose_name='обоснования')),
                ('laws', models.ManyToManyField(related_name='solution_methods', to='problems.Law', verbose_name='законы')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_methods', to='problems.problem', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'способ решения',
                'verbose_name_plural': 'способы решения',
                'ordering': ['problem_id', 'order', 'id'],
            },
        ),
    ]
