# Generated by Django 3.2.4 on 2026-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0026_justification_law_problemsolutionmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemsolutionmethod',
            options={'ordering': ['problem_id', 'order', 'id'], 'verbose_name': 'вариант решения', 'verbose_name_plural': 'варианты решения'},
        ),
        migrations.AlterField(
            model_name='problemsolutionmethod',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='название варианта'),
        ),
    ]
