# Generated by Django 3.2.4 on 2026-04-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_auto_20260402_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemsolutionmethod',
            options={'ordering': ['problem_id', 'order', 'id'], 'verbose_name': 'способ решения', 'verbose_name_plural': 'способы решения'},
        ),
        migrations.AddField(
            model_name='problemsolutionmethod',
            name='excluded_justifications',
            field=models.ManyToManyField(blank=True, related_name='excluded_in_solution_methods', to='problems.Justification', verbose_name='исключённые обоснования'),
        ),
        migrations.AlterField(
            model_name='problemsolutionmethod',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='название способа'),
        ),
    ]
