# Generated by Django 3.2.4 on 2026-04-06 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0028_auto_20260406_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsolutionmethod',
            name='excluded_justifications',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_solution_methods', to='problems.Justification', verbose_name='исключённые обоснования'),
        ),
        migrations.AlterField(
            model_name='problemsolutionmethod',
            name='justifications',
            field=models.ManyToManyField(blank=True, related_name='solution_methods', to='problems.Justification', verbose_name='обязательные обоснования'),
        ),
        migrations.AlterField(
            model_name='problemsolutionmethod',
            name='laws',
            field=models.ManyToManyField(blank=True, related_name='solution_methods', to='problems.Law', verbose_name='законы'),
        ),
        migrations.CreateModel(
            name='JustificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='название группы')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('min_selected', models.PositiveSmallIntegerField(default=1, verbose_name='минимум выбрать')),
                ('max_selected', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='максимум выбрать')),
                ('justifications', models.ManyToManyField(blank=True, related_name='justification_groups', to='problems.Justification', verbose_name='обоснования группы')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justification_groups', to='problems.problemsolutionmethod', verbose_name='способ решения')),
            ],
            options={
                'verbose_name': 'группа обоснований',
                'verbose_name_plural': 'группы обоснований',
                'ordering': ['method_id', 'order', 'id'],
            },
        ),
    ]
