# Generated by Django 3.2.4 on 2023-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_variant_show_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='комментарии'),
        ),
    ]
