# Generated by Django 3.2.4 on 2023-03-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_auto_20230308_1253'),
        ('variants', '0003_alter_variant_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'default_related_name': 'variants', 'verbose_name': 'вариант', 'verbose_name_plural': 'варианты'},
        ),
        migrations.AlterField(
            model_name='variant',
            name='problems',
            field=models.ManyToManyField(related_name='variants', to='problems.Problem', verbose_name='задачи'),
        ),
    ]
