# Generated by Django 3.2.4 on 2023-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0004_auto_20230320_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='complexity',
            field=models.FloatField(blank=True, default=0, verbose_name='сложность'),
        ),
    ]
