# Generated by Django 3.2.4 on 2023-03-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0005_auto_20230325_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата добавления'),
        ),
    ]
