# Generated by Django 3.2.4 on 2023-04-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0006_alter_variant_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='answer_slug',
            field=models.SlugField(blank=True, default='foxy', max_length=4, verbose_name='slug для получения ответов'),
        ),
    ]
