# Generated by Django 3.2.4 on 2023-04-01 18:07

from django.db import migrations, models
import variants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0007_variant_answer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='answer_slug',
            field=models.SlugField(blank=True, default='foxy', max_length=4, validators=[variants.validators.validate_answer_slug], verbose_name='slug для получения ответов'),
        ),
    ]
