# Generated by Django 3.2.4 on 2023-04-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0008_alter_variant_answer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='variants_pdf/', verbose_name='PDF файл варианта'),
        ),
    ]
