# Generated by Django 3.2.4 on 2023-04-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0009_variant_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='pdf_file',
        ),
    ]
