# Generated by Django 3.2.4 on 2023-04-16 15:49

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0019_auto_20230308_1253'),
        ('variants', '0010_remove_variant_pdf_file'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='variant',
            name='problems',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='variants', to='problems.Problem', verbose_name='задачи'),
        ),
    ]
