# Generated by Django 3.2.4 on 2023-06-03 21:52

from django.db import migrations, models
import variants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0012_variant_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='answer_slug',
            field=models.SlugField(blank=True, default='', max_length=4, validators=[variants.validators.validate_answer_slug], verbose_name='slug для получения ответов'),
        ),
    ]
