# Generated by Django 3.2.4 on 2024-03-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0013_alter_variant_answer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='комментарии'),
        ),
    ]
