# Generated by Django 3.2.4 on 2024-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0014_variant_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='заметки'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
