# Generated by Django 3.2.4 on 2025-08-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0015_auto_20240318_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sort_by_complexity',
            field=models.BooleanField(default=False, verbose_name='отсортировать по нарастанию сложности'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='показать в списке вариантов'),
        ),
    ]
