# Generated by Django 3.2.4 on 2025-10-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0016_auto_20250806_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='полный вариант'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='показать в списке вариантов'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='show_answers',
            field=models.BooleanField(default=False, verbose_name='показать решения'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sort_by_complexity',
            field=models.BooleanField(default=True, verbose_name='отсортировать по нарастанию сложности'),
        ),
    ]
