# Generated by Django 3.2.4 on 2026-04-09 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('variants', '0017_auto_20251017_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='owner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_variants',
                to=settings.AUTH_USER_MODEL,
                verbose_name='создатель',
            ),
        ),
    ]
