# Generated by Django 3.2.4 on 2026-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0018_variant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='show_problem_links',
            field=models.BooleanField(default=False, verbose_name='отображать в варианте номера задач со ссылками'),
        ),
    ]
