# Generated by Django 3.2.4 on 2026-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0019_variant_show_problem_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='show_problem_links',
        ),
        migrations.AddField(
            model_name='variant',
            name='show_complexity',
            field=models.BooleanField(default=False, verbose_name='отображать в варианте сложность'),
        ),
        migrations.AddField(
            model_name='variant',
            name='show_max_score',
            field=models.BooleanField(default=False, verbose_name='отображать в варианте максимум баллов'),
        ),
        migrations.AddField(
            model_name='variant',
            name='show_original_number',
            field=models.BooleanField(default=False, verbose_name='отображать в варианте оригинальный номер'),
        ),
        migrations.AddField(
            model_name='variant',
            name='show_solution_link',
            field=models.BooleanField(default=False, verbose_name='отображать в варианте ссылку на решение'),
        ),
        migrations.AddField(
            model_name='variant',
            name='show_source',
            field=models.BooleanField(default=False, verbose_name='отображать в варианте источник'),
        ),
        migrations.AddField(
            model_name='variant',
            name='show_type',
            field=models.BooleanField(default=False, verbose_name='отображать в варианте тип'),
        ),
    ]
