# Generated by Django 3.2.4 on 2026-04-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0020_auto_20260410_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sort_by_type',
            field=models.BooleanField(default=False, verbose_name='отсортировать по типу'),
        ),
    ]
