# Generated by Django 3.2.4 on 2026-04-11 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('allow_student_self_signup', models.BooleanField(default=True, verbose_name='разрешить саморегистрацию учеников')),
                ('allow_teacher_self_signup', models.BooleanField(default=True, verbose_name='разрешить саморегистрацию учителей')),
                ('require_email_on_signup', models.BooleanField(default=True, verbose_name='требовать почту при регистрации')),
            ],
            options={
                'verbose_name': 'настройки платформы',
                'verbose_name_plural': 'настройки платформы',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'ученик'), ('teacher', 'учитель')], default='student', max_length=20, verbose_name='роль')),
                ('teacher_approval_status', models.CharField(choices=[('not_required', 'не требуется'), ('pending', 'ожидает одобрения'), ('approved', 'одобрен'), ('rejected', 'отклонен')], default='not_required', max_length=20, verbose_name='статус одобрения учителя')),
                ('teacher_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='когда одобрен')),
                ('statistics_share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='токен публичной статистики')),
                ('statistics_share_enabled', models.BooleanField(default=False, verbose_name='разрешить внешнюю ссылку на статистику')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
                ('teacher_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_profiles', to=settings.AUTH_USER_MODEL, verbose_name='кто одобрил')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='TeacherStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_student_links', to=settings.AUTH_USER_MODEL, verbose_name='кем создана связь')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL, verbose_name='ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to=settings.AUTH_USER_MODEL, verbose_name='учитель')),
            ],
            options={
                'verbose_name': 'связь учителя и ученика',
                'verbose_name_plural': 'связи учителей и учеников',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('students', models.ManyToManyField(blank=True, related_name='student_study_groups', to=settings.AUTH_USER_MODEL, verbose_name='ученики')),
                ('teachers', models.ManyToManyField(blank=True, related_name='managed_study_groups', to=settings.AUTH_USER_MODEL, verbose_name='учителя')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='teacherstudentlink',
            constraint=models.UniqueConstraint(fields=('teacher', 'student'), name='unique_teacher_student_link'),
        ),
    ]
