# Generated by Codex on 2026-04-11

from django.db import migrations
from django.utils import timezone


def seed_platform_settings_and_profiles(apps, schema_editor):
    PlatformSettings = apps.get_model('accounts', 'PlatformSettings')
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    PlatformSettings.objects.get_or_create(
        pk=1,
        defaults={
            'allow_student_self_signup': True,
            'allow_teacher_self_signup': True,
            'require_email_on_signup': True,
        },
    )

    now = timezone.now()
    for user in User.objects.all():
        defaults = {
            'role': 'teacher' if user.is_staff else 'student',
            'teacher_approval_status': 'approved' if user.is_staff else 'not_required',
            'teacher_approved_at': now if user.is_staff else None,
        }
        UserProfile.objects.get_or_create(user=user, defaults=defaults)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            seed_platform_settings_and_profiles,
            reverse_code=noop_reverse,
        ),
    ]
