# Generated by Codex on 2026-04-12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_platform_settings_and_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='токен приглашения'),
        ),
    ]
