# Generated by Django 3.2.4 on 2026-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studygroup_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_users_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='когда админ смотрел список пользователей'),
        ),
    ]
